### ISSUE TITLE
Firewall working but matchmaking doesnt work and/or is extremely slow.

### ISSUE THREAD

**Issue by feetusbeetus** [fswdevl/Destiny-2-SDR-Matchmaking-Firewall#11]
Hey, I've set this up and my firewall works perfectly but when I matchmake it takes 8-10 minutes then gives me a mongoose error (9/10 times otherwise it matchmakes) 

I've tried troubleshooting this and I found that when I get a fireteam member to leave the team while we're matchmaking, we matchmake instantly. I really can't seem to figure this problem out.

I'm using both real and accounts with almost equal stats so that isn't an issue either. I'm using Microsoft Azure cloud VM on an Asian server so my VPN routes through Asia with ~100 ping on SpeedTest. Does that have to do something with this issue? Should I try creating the Cloud VM located in my own country?

I'm on PC btw.

**Comment by fswdevl** [comment]
Matchmaking is always slow during peak population. If takes more than 2 minutes just cancel and restart matchmaking.

**Comment by feetusbeetus** [comment]
Would you recommend setting the VPS server location to where there are less players for example Korea or Australia?

**Comment by fswdevl** [comment]
The VPS should be fairly close to your location. If your ping is too high
you will not be able to matchmake at all.
