### ISSUE TITLE
Matchmaking problem

### ISSUE THREAD

**Issue by kmlalpr** [fswdevl/Destiny-2-SDR-Matchmaking-Firewall#14]
Hi,
i created a VM (ubuntu server) and installed the script. Everything is okey, created ovpn and uploaded to my router (DSL - AC51) . I have 2 console one of them is ps4 the other one is ps5. Both of them connected to router and i set it up with sudo bash d2firewall.sh -a setup command. When sniff comes, i am joining  ps4 to ps5 and getting ID's. Everything is fine for now, after that im using -a sniff command for other teammates. Getting id's and pressing enter. When firewall is okey, both consoles do not match each other. Waiting like 3-4 minutes and trying again, same. Constantly Evaluating/searching. What am i missing? am i have to use 2 vpn? or same console? Also how can i use it without openvpn? Am i have to change my router?Thank you.

**Comment by fswdevl** [comment]
This is normal behavior. On the first card it is always slow. If it takes you more than 2 minutes to match make then cancel and restart. After first card is completed use anchors (1 person on each team with 7 wins). You should also be using queue dodging techniques to balance out the wins for each team. (You can google this info).

**Comment by mCutaa** [comment]
hey @kmlalpr did you end up getting the teams to matchmake? Currently having the same issue after testing for about 1.5 hours during both peak and non-peak population times. Have been backing out after about 2-3 mins. Both teams get to "evaluating" but never join each other.

**Comment by Immortalists** [comment]
@mCutaa do you have discord? I can assist you

**Comment by mCutaa** [comment]
yeah it's Cutaa#6639, that would really appreciate it

**Comment by Immortalists** [comment]
I've added you. Should've come through just now.

**Comment by unknownoddity** [comment]
Would you mind adding me on Discord too? :) DaisytheEGirl#0640 :)
