### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by Gastraphete** [fswdevl/Destiny-2-SDR-Matchmaking-Firewall#15]
Hi, I much appreciate the work you've done on this project. I ran into a few errors while setting up the script, as I was unable to open up the link that was given, nor was I able to find the file for the alternative method as shown in the screenshots.
![404](https://user-images.githubusercontent.com/86048599/122368543-493c9480-cf12-11eb-96e4-d4e2e99fee40.PNG)
![No such file](https://user-images.githubusercontent.com/86048599/122368549-49d52b00-cf12-11eb-9871-806007a828ec.PNG)
I opened the port 80 as well and double checked to see if it was active or not.
![Logs](https://user-images.githubusercontent.com/86048599/122370978-5bb7cd80-cf14-11eb-8e58-0cc3ddd150b3.PNG)
Any help here is highly appreciated. I'm running this inside a VM with Ubuntu.

**Comment by mCutaa** [comment]
The file should be saved to the virtual machine anyway. If you list all files with dir you should see that client.ovpn is there. 

I found that the easiest way to get the config file to my host pc was just to upload it to a github repository (follow these steps here https://www.tutsmake.com/upload-project-files-on-github-using-command-line/)

**Comment by fabricemasachs** [comment]
Check if you have cURL installed #7

**Comment by Gastraphete** [comment]
I was able to get the config.ovpn file by opening client.ovpn directly; There was no need to head into the root folder. I appreciate the responses on this topic and will try the other given methods should the need arise.
