### ISSUE TITLE
Config file connection issues

### ISSUE THREAD

**Issue by mCutaa** [fswdevl/Destiny-2-SDR-Matchmaking-Firewall#16]
Hey, champion work with this script. 

I'm fairly sure I've got the setup correct but the config file is failing to connect. I'm using DumaOS with an XR500.

In the Advanced settings for Hybrid VPN setup, I get a fatal error if I don't use a username & password. 
When testing the config file on the OpenVPN desktop GUI for windows, I get a TLS handshake error.

Have tried running the openVPN setup manually and configuring a password, with no luck also.

Any advice would be amazing <3

**Comment by Sam-x89** [comment]
forward port 1194.

**Comment by fswdevl** [comment]
Use client for both username and password. No need to setup openVPN with a
username/password. Also make sure you copied or downloaded the config
correctly. XR500 also needs to be updated to DumaOS 3.0 version.

**Comment by mCutaa** [comment]
Cheers for the responses. I've updated my DumaOS to the 3.0 Beta for the XR500. @Sam-x89 what's the workflow for forwarding port 1194? I've tried setting up a port forwarding rule on the DumaOS software but it isn't right. (I'm much better at the programming parts than the internet tech parts)

**Comment by mCutaa** [comment]
^managed to sort out the port forwarding. Can connect to the openVPN server now. Cheers guys <3

**Comment by Melvinbrooks** [comment]
hey mcutaa thanks for youre help the other day.. how did you sort out the port forwarding?

**Comment by Melvinbrooks** [comment]
cant get the config file to work

**Comment by mCutaa** [comment]
hey, I had an AWS instance hosting the vpn. In the AWS menu, there's a tab called security groups. I had to add a new rule to the inbound traffic allowing port 1194 to receive packets from any source. 

While it's possible with AWS and lot's of people here have done it, myself and a few others found that hosting the vpn on AWS didn't work very well with this code if you're on PlayStation. If you are using PS I'd recommend hosting on Linode. Although it is $5 or $10 a month, the setup was super smooth & quick and I didn't have to deal with any of the issues I had with AWS.

**Comment by Melvinbrooks** [comment]
I play on Xbox. Would it matter?

Sent from my iPhone

On Jul 16, 2021, at 17:30, mCutaa ***@***.***> wrote:

﻿

hey, I had an AWS instance hosting the vpn. In the AWS menu, there's a tab called security groups. I had to add a new rule to the inbound traffic allowing port 1194 to receive packets from any source.

While it's possible with AWS and lot's of people here have done it, myself and a few others found that hosting the vpn on AWS didn't work very well with this code if you're on PlayStation. If you are using PS I'd recommend hosting on Linode. Although it is $5 or $10 a month, the setup was super smooth & quick and I didn't have to deal with any of the issues I had with AWS.

**Comment by Melvinbrooks** [comment]
I’m using Ubuntu and I can’t find the certificate file to plug into my router. I have a openvpn install.ah file in Home but no certificate

Sent from my iPhone

On Jul 16, 2021, at 20:13, Veгified ✔ ***@***.***> wrote:

﻿ I play on Xbox. Would it matter?

Sent from my iPhone

On Jul 16, 2021, at 17:30, mCutaa ***@***.***> wrote:

﻿

hey, I had an AWS instance hosting the vpn. In the AWS menu, there's a tab called security groups. I had to add a new rule to the inbound traffic allowing port 1194 to receive packets from any source.

While it's possible with AWS and lot's of people here have done it, myself and a few others found that hosting the vpn on AWS didn't work very well with this code if you're on PlayStation. If you are using PS I'd recommend hosting on Linode. Although it is $5 or $10 a month, the setup was super smooth & quick and I didn't have to deal with any of the issues I had with AWS.

**Comment by mCutaa** [comment]
I'm not too sure about Xbox, you might just have to go through the set up process and see if it works at the end. For me, everything was set up correctly on AWS but my two consoles would search/evaluate but never match each other. As soon as I swapped to linode it worked instantly.

**Comment by mCutaa** [comment]
If you've run the -a setup command and got to the point where it's told you to download the client config file, the file should just be saved to your desktop. What files show up when you type in "dir" from the home directory?

**Comment by Melvinbrooks** [comment]
The only file I see is an openvpn-Ubuntu-install.sh

Sent from my iPhone

On Jul 17, 2021, at 04:43, mCutaa ***@***.***> wrote:

﻿

If you've run the -a setup command and got to the point where it's told you to download the client config file, the file should just be saved to your desktop. What files show up when you type in "dir" from the home directory?

**Comment by mCutaa** [comment]
right. If the setup command no longer asks if you want to set up openvpn, it might just be easiest to make a new ubuntu server and start the setup from scratch again. Send through your discord if you want, happy to help out with the setup

**Comment by Melvinbrooks** [comment]
Thanks. My discord is oneeyedflask#4524

Sent from my iPhone

On Jul 17, 2021, at 20:02, mCutaa ***@***.***> wrote:

﻿

right. If the setup command no longer asks if you want to set up openvpn, it might just be easiest to make a new ubuntu server and start the setup from scratch again. Send through your discord if you want, happy to help out with the setup

**Comment by Sam-x89** [comment]
just run the openvpn file separately. like actually open the script and inspect and see with indecencies you need before running the script.

**Comment by Melvinbrooks** [comment]
When I went to the script I don’t see the start or end certificate or username password and that I need to plug into my hybrid vpn settings on my router.

Sent from my iPhone

On Jul 18, 2021, at 10:28, Sam ***@***.***> wrote:

﻿

just run the openvpn file separately. like actually open the script and inspect and see with indecencies you need before running the script.

**Comment by Sam-x89** [comment]
that script actually download a separate vpn script which then makes a file and you then upload that file to your router. like i said inspect the script and check the vpn section and download the other script and run it separately.
