### ISSUE TITLE
Host ID sniffing

### ISSUE THREAD

**Issue by mCutaa** [fswdevl/Destiny-2-SDR-Matchmaking-Firewall#17]
Hey fswdevl, sorry for spamming with comments.

I have my PS4 & PS5 connected to the openvpn server (hosted on an Ubuntu AWS instance). However sniffing the two host ID's through the setup action has only worked once over a few hours of testing. I am joining the two accounts in orbit while the snif is running. 

![image](https://user-images.githubusercontent.com/80436324/124059385-5c04ac80-da6e-11eb-92d0-88e5f4bd4a6d.png)

I've read the closed issues which touch on how the setup should be run, and have sourced my network/netmask from the tun0 section of ifconfig. Is there something obviously incorrect with the setup?

**Comment by fswdevl** [comment]
If you hit enter it will use the default values for openvpn. You don't have
to specifically put anything. Also double check if your consoles are
actually connected.

**Comment by mCutaa** [comment]
I've fixed it. Consoles were both connected to the server but the instance timezone was not the same for where I live. Difference in time was ruining the sniff. Hopefully this can help someone in future :)

**Comment by Melvinbrooks** [comment]
@mCutaa may i ask a question? where it says enter network, where to I find that number?

**Comment by Melvinbrooks** [comment]
do*

**Comment by mCutaa** [comment]
you can find that number using ifconfig, but as fswdevl said it also works if you don't put in anything and just use the default value.
