### ISSUE TITLE
Matchmaking Errors

### ISSUE THREAD

**Issue by Immortalists** [fswdevl/Destiny-2-SDR-Matchmaking-Firewall#18]
Hello,

I've been having issues with matchmaking on PC and I have looked into your already resolved issues in this thread.

I am currently running the script on AWS. My teams are reaching 6/6 on one side and 3/6 on other side, then it will drop to 3/6 on both sides. 

I can attach a photo of my IP tables list, but I am unsure of what I may be missing. 

Any suggestions?

**Comment by Immortalists** [comment]
Actually resolved. I had to manually add all ID's because it was incorrectly adding them into the IP tables.

**Comment by Melvinbrooks** [comment]
@Immortalists hey brother, can you help me set this up for box. I'm struggling lol
