### ISSUE TITLE
Matchmaking 

### ISSUE THREAD

**Issue by xvikings** [fswdevl/Destiny-2-SDR-Matchmaking-Firewall#22]
Hello 
I've being trying to run the script for a long time and I finally did it the script is working and everything is good but the matchmaking takes forever to find my other PS,  I'm using 2 PS console btw

**Comment by fswdevl** [comment]
It's normal for it to be slow on fridays and saturdays during peak
populations. After you finish the first card you will need to use anchors
(1 person with 7 wins on both teams) to speed up the subsequent runs.

**Comment by xvikings** [comment]
Ok thank u I thought if i get a better vps or run 2 host in different network it will be faster any way thank u for ur help

**Comment by mCutaa** [comment]
Hey @Asec6 would you mind having a chat on discord (Cutaa#6639) about the running this script on PS? I've got everything set up correctly (and have tested that the firewall works) but it's never matched the two teams together after a lot of testing. Would be amazing <3
