### ISSUE TITLE
[PC] PCs are not matching against eachother resulting in constant mongoose errors.

### ISSUE THREAD

**Issue by fijeeto** [fswdevl/Destiny-2-SDR-Matchmaking-Firewall#8]
Thank you for all the efforts on this script! I'm using this on Microsft Azure and have successfully set everything up until the point where I start matchmaking and my **PCs are unable to match each other which results in mongoose.**

My firewall works perfectly as I am not able to find anybody. I am also able to see my PC's IDs when I list them. 

One issue I found was that even though the IDs are in the list, when I restrict the matchmaking, I am unable to join the fireteam and it shows me the "Nat type error". In hopes to country this, I enabled UPnP on my OpenWRT router but still no fix. Is this supposed to happen even though both my PCs are in the list?

Could you please help me figure the issue out here? My router log is good with no errors and the OpenVPN setup is successful. **Everything works but matchmaking.**

I have tried matchmaking strikes, tower, crucible almost all the gamemodes. I'm waiting for your help<3

**Comment by fijeeto** [comment]
![Capture](https://user-images.githubusercontent.com/85457086/120938467-79c14900-c730-11eb-9e44-2020dc64b5a2.PNG)

**Comment by fswdevl** [comment]
Try running the setup again and auto sniff the IDS of each PC.

**Comment by fijeeto** [comment]
Ive just tried that. No luck. Even tried entering both the PC's ID manually. but no luck.

I'm using stock openWrt settings. Is there something specific I need to set up for this to work?

**Comment by fswdevl** [comment]
When auto sniffing do you see any ids show on the screen?

**Comment by fijeeto** [comment]
Yes, I see the same IDs as I do when I run setup command. I see both my PC'c ids.

Just making sure, in setup where it asks for network/netmask its asking for subnet, right (255.255.255.0 in my case)?

**Comment by rwadud** [comment]
That totally depends on the setup but 255.255.255.0 does not seem right. 
Are using this through Microsoft Azure through an Ubuntu VM?
Are you using openVPN?

**Comment by fswdevl** [comment]
That totally depends on the setup but 255.255.255.0 does not seem right.
Are using this through Microsoft Azure through an Ubuntu VM?
Are you using openVPN?

**Comment by fijeeto** [comment]
When I IP config through my windows PC I get the subnet mask as 255.255.255.0.

I've made an ubuntu VM on Microsoft Azure which im connecting through an RDP from my Windows PC.

Yes, I am using OpenVPN on my OpenWrt router.

**Comment by fswdevl** [comment]
If you are connecting the consoles to the Ubuntu VM via OpenVPN then just
hit enter on the network/netmask step. It will use the default setting for
OpenVPN which is 10.8.0.0/24.
