### ISSUE TITLE
Router goes offline

### ISSUE THREAD

**Issue by Sam-x89** [fswdevl/Destiny-2-SDR-Matchmaking-Firewall#9]
Hey fswdevl,
setting this up was quick education for me because I'm new to all of this and got quite far till I encountered some problems.
I have small ubuntu installation on a VM with the network being Bridged Adepter.

regarding the scripts setup I had some of the following confusions:
(psn) for your network/netmask: "consoleip/24"? "routerIP/24"? "publicIP/24"?
also if I am behind NAT connection, do I still use my publicIP aka modemIP or the router IP?
also if I am using this in a local home network I forwarded UDP/1194 on my router and modem. Do I need to forward any other ports? Because the moment I enable my OpenVPN on my router, then the router goes offline.

Is there a more detailed guide somewhere?

**Comment by fswdevl** [comment]
If you are doing this on a local vm or linux pc you need to use your
private IP address of the VM that connects to your router.
You need to ensure that the PC that hosts the VM does not connect to the
VPN or it will create a loop and you will lose internet access.
Only the consoles must connect to the VPN. If your router does not support
split tunneling or hybrid vpn then this will not work.

**Comment by Sam-x89** [comment]
thanks, this makes a lot of sense now! which router would you recommend?

**Comment by fswdevl** [comment]
Any netduma/dumaos router will do. But you can avoid this issue by using a
VPS instead.
